server:
  port: 8888
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${EUREKA:localhost}:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: estudiante
          uri: lb://estudiantes
          predicates:
            - Path=/api/estudiantes/**
        - id: Cuota
          uri: lb://Cuota
          predicates:
            - Path=/api/cuotas/**
        - id: Examen
          uri: lb://Examen
          predicates:
            - Path=/api/notas/**